test_format = 1.0

[default]

# ------------
# Tests to run
# ------------

preinstall = """
    sudo yunohost tools update apps
    sudo yunohost app install https://github.com/YunoHost-Apps/synapse_ynh/ \
        -a "domain=domain.tld&init_main_permission=all_users&server_name=domain.tld&is_free_registration=false" --force
    """

# -------------------------------
# Default args to use for install
# -------------------------------

args.botadmins = "@johndoe:server.name"
args.botusers = "server.name"

# -------------------------------
# Commits to test upgrade from
# -------------------------------

# This is an additional test suite
[multiple_botusers]

preinstall = """
    sudo yunohost tools update apps
    sudo yunohost app install https://github.com/YunoHost-Apps/synapse_ynh/ \
        -a "domain=domain.tld&init_main_permission=all_users&server_name=domain.tld&is_free_registration=false" --force
    """

# On additional tests suites, you can decide to run only specific tests

only = ["install.subdir"]

args.botadmins = "@johndoe:server.name,janedoe:other.host"
args.botusers = "@john:server.name,@jdoe:server.name,@janedoe:server.name"
