#!/bin/bash
source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# RETRIEVE ARGUMENTS
#=================================================

install_dir=$(ynh_app_setting_get --key=install_dir)

#=================================================
# SPECIFIC GETTERS FOR TOML SHORT KEY
#=================================================

#=================================================
# SPECIFIC VALIDATORS FOR TOML SHORT KEYS
#=================================================

#=================================================
# SPECIFIC SETTERS FOR TOML SHORT KEYS
#=================================================

set__avatar() {
    if [ "$avatar" == "default" ]; then
        avatar="mxc://maunium.net/nIdEykemnwdisvHbpxflpDlC"
    fi
    ynh_app_setting_set --key="avatar" --value="$avatar"
}

#=================================================
# OVERWRITING APPLY STEP
#=================================================

ynh_app_config_apply() {
    _ynh_app_config_apply
    chmod 400 "$install_dir/config.yaml"
    chown "$app:$app" "$install_dir/config.yaml"

    ynh_config_add --template="config.yaml.j2" --destination="$install_dir/config.yaml" --jinja
    "$install_dir/$APP_BIN" -g -c "$install_dir/config.yaml" -r "/etc/matrix-$synapse_instance/app-service/$app.yaml"
    local synapse_install_dir=$(ynh_app_setting_get --app "$synapse_instance" --key "install_dir")
    "$synapse_install_dir/update_synapse_for_appservice.sh" || ynh_die "Synapse can't restart with the appservice configuration"
    ynh_store_file_checksum "/etc/matrix-$synapse_instance/app-service/$app.yaml"
}

ynh_app_config_run $1
