#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

# Retrieve some values from selected Synapse instance and store them
# NB: hs_ stands for Homeserver
hs_server_name=$(ynh_app_setting_get --app $synapse_instance --key server_name)
synapse_install_dir=$(ynh_app_setting_get --app $synapse_instance --key "install_dir")
hs_domain=$(ynh_app_setting_get --app $synapse_instance --key domain)
ynh_app_setting_set --key=hs_server_name --value=$hs_server_name
ynh_app_setting_set --key=hs_domain --value=$hs_domain

#=================================================
# SET STANDARD SETTINGS FROM DEFAULT CONFIG
#=================================================

appserviceid=$app

ynh_app_setting_set_default --key="avatar" --value="mxc://maunium.net/nIdEykemnwdisvHbpxflpDlC"
ynh_app_setting_set_default --key="displayname" --value="Discord bridge bot"
ynh_app_setting_set_default --key="relays" --value=""

#=================================================
# APP "BUILD" (DEPLOYING SOURCES, VENV, COMPILING ETC)
#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

# Download, check integrity, uncompress and patch the source from manifest.toml
ynh_setup_source --dest_dir="$install_dir"

chmod 750 "$install_dir/$APP_BIN"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_systemd

yunohost service add $app --description="Matrix Discord pupetting bridge for YunoHost" --log="/var/log/$app/$app.log"

# Use logrotate to manage application logfile(s)
ynh_config_add_logrotate  "/var/log/$app/$app.log"

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration..."

ynh_config_add --template="config.yaml.j2" --destination="$install_dir/config.yaml" --jinja
chmod 400 "$install_dir/config.yaml"
chown "$app:$app" "$install_dir/config.yaml"

generate_registration

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --action="start"

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression "Installation of $app completed"
