#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

# Retrieve some values from selected Synapse instance and store them
server_name=$(ynh_app_setting_get --app $synapse_instance --key server_name)
domain=$(ynh_app_setting_get --app $synapse_instance --key domain)
ynh_app_setting_set --key=server_name --value=$server_name
ynh_app_setting_set --key=domain --value=$domain
synapse_db_name="$(get_synapse_db_name $synapse_instance)"

synapse_version=$(yunohost app info $synapse_instance | grep -oP "version:\s*\K.*")

#=================================================
# SET STANDARD SETTINGS FROM DEFAULT CONFIG
#=================================================

# Die if Synapse is too outdated (1.22.0 is required for ephemeral_events)
if dpkg --compare-versions $synapse_version lt 1.22.0; then
  ynh_die "Unsupported Synapse version. Please upgrade."
fi

appserviceid=$app
if dpkg --compare-versions $synapse_version ge 1.97.0; then
  async_media="true"
else
  async_media="false"
fi

listrelay="*"
listadmin="$botadmin"
listuser="$botusers"

ynh_app_setting_set --key=async_media --value=$async_media
ynh_app_setting_set --key=listrelay --value=$listrelay
ynh_app_setting_set --key=listadmin --value=$listadmin
ynh_app_setting_set --key=listuser --value=$listuser

#=================================================
# APP "BUILD" (DEPLOYING SOURCES, VENV, COMPILING ETC)
#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_app_setting_set --key=listuser --value=$listuser
# Download, check integrity, uncompress and patch the source from manifest.toml
ynh_setup_source --dest_dir="$install_dir"

chmod 750 "$install_dir/$APP_BIN"
#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chown -R $app:www-data "$install_dir"
#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_systemd

yunohost service add $app --description="Matrix Discord pupetting bridge for YunoHost" --log="/var/log/$app/$app.log"

# Use logrotate to manage application logfile(s)
ynh_config_add_logrotate  "/var/log/$app/$app.log"  $app/$app
#REMOVEME? Assuming ynh_config_add_logrotate is called, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chmod -R 600 "/var/log/$app"
#REMOVEME? Assuming ynh_config_add_logrotate is called, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chmod 700 "/var/log/$app"
#REMOVEME? Assuming ynh_config_add_logrotate is called, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chown -R $app:$app /var/log/$app

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration..."

ynh_config_add --template="config.yaml" --destination="$install_dir/config.yaml"

#REMOVEME? Assuming the file is setup using ynh_config_add, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chmod 400 "$install_dir/config.yaml"
#REMOVEME? Assuming the file is setup using ynh_config_add, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chown $app:$app "$install_dir/config.yaml"

# This calls allows to set multiple users during install question "botusers" specifying them separated by a comma
set__listuser
set__listrelay
set__listadmin

$install_dir/$APP_BIN -g -c $install_dir/config.yaml -r /etc/matrix-$synapse_instance/app-service/$app.yaml
/opt/yunohost/matrix-$synapse_instance/update_synapse_for_appservice.sh || ynh_die "Synapse can't restart with the appservice configuration"

#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chown -R $app:$app "$install_dir"
ynh_store_file_checksum "/etc/matrix-$synapse_instance/app-service/$app.yaml"
ynh_store_file_checksum "$install_dir/config.yaml"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service=$app --action="start"

# Wait until the synapse user is created
sleep 30

# (Note that, by default, non-admins might not have your homeserver's permission to create Spaces.)
if [ "$bot_synapse_adm" = true ]
then
  ynh_psql_db_shell $synapse_db_name <<< "UPDATE users SET admin = 1 WHERE name = ""$botname"";"
fi

ynh_systemctl --service=$app --action="restart"

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression "Installation of $app completed"
