#!/bin/bash

# Keep this path for calling _common.sh inside the execution's context of backup and restore scripts
source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

hs_server_name=$(ynh_app_setting_get --key=hs_server_name)
synapse_install_dir=$(ynh_app_setting_get --app $synapse_instance --key "install_dir")

synapse_db_name="$(get_synapse_db_name $synapse_instance)"
bot_synapse_db_user="@$botname:$hs_server_name"

#=================================================
# RESTORE THE APP MAIN DIR
#=================================================
ynh_script_progression "Restoring the app main directory..."

ynh_restore "$install_dir"

chmod 750 "$install_dir/$APP_BIN"

#=================================================
# RESTORE THE POSTGRESQL DATABASE
#=================================================
ynh_script_progression "Restoring the PostgreSQL database..."

ynh_psql_db_shell  < "./db.sql"

#=================================================
# REGISTER SYNAPSE APP-SERVICE
#=================================================
ynh_script_progression "Registering Synapse app-service"

generate_registration

#=================================================
# RESTORE SYSTEM CONFIGURATIONS
#=================================================

ynh_script_progression "Restoring system configurations related to $app..."
ynh_restore "/etc/systemd/system/$app.service"
systemctl enable $app.service --quiet

ynh_restore "/etc/logrotate.d/$app"

# The logs can be huge, restore them only if included in the backups
mkdir -p "/var/log/$app"
chown $app:www-data "/var/log/$app"
ynh_restore "/var/log/$app/" || true

yunohost service add $app --description="Matrix Discord pupetting bridge for YunoHost" --log="/var/log/$app/$app.log"

#=================================================
# RELOAD NGINX AND PHP-FPM OR THE APP SERVICE
#=================================================
ynh_script_progression "Reloading $app's service..."

ynh_systemctl --action="start"

# Wait until the synapse user is created
sleep 30
# (Note that, by default, non-admins might not have your homeserver's permission to create communities.)
if [ "$bot_synapse_adm" == "1" ]
then
  ynh_psql_db_shell $synapse_db_name <<< "UPDATE users SET admin = 1 WHERE name = '$botname';"
fi
ynh_systemctl --action="restart"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Restoration completed for $app"
