#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

synapse_install_dir=$(ynh_app_setting_get --app $synapse_instance --key "install_dir")
appserviceid=$app

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --action="stop"

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================

if ynh_app_upgrading_from_version_before "0.7.7~ynh1"; then
    migrate_permissions_to_appsettings
    rename_setting "domain" "hs_domain"
    rename_setting "server_name" "hs_server_name"
    ynh_app_setting_set_default --key="avatar" --value="mxc://maunium.net/nIdEykemnwdisvHbpxflpDlC"
    ynh_app_setting_set_default --key="displayname" --value="Discord bridge bot"
fi

#=================================================
# "REBUILD" THE APP (DEPLOY NEW SOURCES, RERUN NPM BUILD...)
#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================

ynh_setup_source --dest_dir="$install_dir"

chmod 750 "$install_dir/$APP_BIN"

#=================================================
# UPDATE A CONFIG FILE
#=================================================
ynh_script_progression "Updating $app's configuration files..."

ynh_config_add --template="config.yaml.j2" --destination="$install_dir/config.yaml" --jinja
chmod 400 "$install_dir/config.yaml"
chown "$app:$app" "$install_dir/config.yaml"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_systemd

yunohost service add $app --description="Matrix Discord pupetting bridge for YunoHost" --log="/var/log/$app/$app.log"

# Use logrotate to manage application logfile(s)
ynh_config_add_logrotate


#=================================================
# REGISTER SYNAPSE APP-SERVICE
#=================================================
ynh_script_progression "Registering Synapse app-service"

generate_registration

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
